"""initial

Revision ID: 427415a85811
Revises: 
Create Date: 2026-04-26 11:27:07.381189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '427415a85811'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rag_queries')
    op.drop_table('role_permissions')
    op.drop_index('idx_req_proc', table_name='procedure_requirements')
    op.drop_table('procedure_requirements')
    op.drop_table('ai_settings')
    op.drop_table('system_logs')
    op.drop_index('idx_step_proc', table_name='procedure_steps')
    op.drop_table('procedure_steps')
    op.drop_index('code', table_name='procedures')
    op.drop_index('idx_proc_name', table_name='procedures')
    op.drop_table('procedures')
    op.drop_table('conversation_sessions')
    op.drop_index('idx_rag_chunk', table_name='rag_retrievals')
    op.drop_index('idx_rag_query', table_name='rag_retrievals')
    op.drop_table('rag_retrievals')
    op.drop_table('rag_generation_logs')
    op.drop_index('email', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('permissions')
    op.drop_index('idx_chunk_source', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('idx_doc_proc', table_name='document_sources')
    op.drop_table('document_sources')
    op.drop_index('idx_msg_session', table_name='messages')
    op.drop_table('messages')
    op.drop_table('feedback_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_records',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('message_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', mysql.TEXT(), nullable=True),
    sa.Column('is_reviewed', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', mysql.CHAR(length=36), nullable=True),
    sa.Column('reviewed_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name='feedback_records_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='feedback_records_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('messages',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('session_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('role', mysql.ENUM('user', 'assistant'), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('token_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('context_chunks', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], name='messages_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_msg_session', 'messages', ['session_id'], unique=False)
    op.create_table('document_sources',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('procedure_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('source_url', mysql.TEXT(), nullable=True),
    sa.Column('doc_number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('issuer', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('issue_date', sa.DATE(), nullable=True),
    sa.Column('version', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('is_latest', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('processing_status', mysql.ENUM('pending', 'chunked', 'embedded', 'failed'), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], name='document_sources_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_doc_proc', 'document_sources', ['procedure_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('source_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('chunk_index', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('section', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('chunk_type', mysql.ENUM('requirement', 'step', 'general'), nullable=True),
    sa.Column('token_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('embedding', mysql.JSON(), nullable=True),
    sa.Column('embedding_status', mysql.ENUM('pending', 'done', 'error'), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['document_sources.id'], name='document_chunks_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_chunk_source', 'document_chunks', ['source_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('module', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('full_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('avatar_url', mysql.TEXT(), nullable=True),
    sa.Column('role', mysql.ENUM('user', 'admin'), server_default=sa.text("'user'"), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('email_verified', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('email_verified_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_login_at', mysql.DATETIME(), nullable=True),
    sa.Column('login_fail_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('locked_until', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('email', 'users', ['email'], unique=True)
    op.create_table('rag_generation_logs',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('query_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('message_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('model', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('prompt', mysql.TEXT(), nullable=True),
    sa.Column('response', mysql.TEXT(), nullable=True),
    sa.Column('prompt_tokens', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completion_tokens', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_tokens', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_time', mysql.FLOAT(), nullable=True),
    sa.Column('is_fallback', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name='rag_generation_logs_ibfk_2'),
    sa.ForeignKeyConstraint(['query_id'], ['rag_queries.id'], name='rag_generation_logs_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rag_retrievals',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('query_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('chunk_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('score', mysql.FLOAT(), nullable=True),
    sa.Column('rerank_score', mysql.FLOAT(), nullable=True),
    sa.Column('retrieval_method', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('model', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('rank_order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name='rag_retrievals_ibfk_2'),
    sa.ForeignKeyConstraint(['query_id'], ['rag_queries.id'], name='rag_retrievals_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_rag_query', 'rag_retrievals', ['query_id'], unique=False)
    op.create_index('idx_rag_chunk', 'rag_retrievals', ['chunk_id'], unique=False)
    op.create_table('conversation_sessions',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('message_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='conversation_sessions_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('procedures',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('domain', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('authority', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('authority_level', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('processing_days', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fee', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('status', mysql.ENUM('draft', 'active', 'inactive'), server_default=sa.text("'draft'"), nullable=True),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=True),
    sa.Column('approved_by', mysql.CHAR(length=36), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name='procedures_ibfk_2'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='procedures_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_proc_name', 'procedures', ['name'], unique=False)
    op.create_index('code', 'procedures', ['code'], unique=True)
    op.create_table('procedure_steps',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('procedure_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('step_order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], name='procedure_steps_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_step_proc', 'procedure_steps', ['procedure_id'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('level', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('service', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('session_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ai_settings',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('config_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('model', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('temperature', mysql.FLOAT(), nullable=True),
    sa.Column('max_tokens', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('procedure_requirements',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('procedure_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('is_required', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], name='procedure_requirements_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_req_proc', 'procedure_requirements', ['procedure_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('permission_id', mysql.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='role_permissions_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rag_queries',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('message_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('original_query', mysql.TEXT(), nullable=True),
    sa.Column('rewritten_query', mysql.TEXT(), nullable=True),
    sa.Column('embedding', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name='rag_queries_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
