"""add_form_url_and_form_chunk_type

Revision ID: 5bb577840176
Revises: b9518f334343
Create Date: 2026-05-02 08:53:58.554592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5bb577840176'
down_revision: Union[str, None] = 'b9518f334343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
