"""add_form_url_and_form_chunk_type

Revision ID: 8b38e1fc4b0f
Revises: 5bb577840176
Create Date: 2026-05-02 08:55:58.698201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8b38e1fc4b0f'
down_revision: Union[str, None] = '5bb577840176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
