"""initial_schema_aligned_with_dd

Revision ID: a72f2a45f435
Revises: d08bcc428234
Create Date: 2026-05-01 10:51:41.496767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a72f2a45f435'
down_revision: Union[str, None] = 'd08bcc428234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
