"""add_form_url_and_form_chunk_type

Revision ID: b9518f334343
Revises: a72f2a45f435
Create Date: 2026-05-01 12:15:24.347018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b9518f334343'
down_revision: Union[str, None] = 'a72f2a45f435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedure_requirements', sa.Column('form_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procedure_requirements', 'form_url')
    # ### end Alembic commands ###
