"""initial_schema_aligned_with_dd

Revision ID: d08bcc428234
Revises: 
Create Date: 2026-05-01 10:51:30.636559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'd08bcc428234'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('module', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('role_permissions',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('permission_id', mysql.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='role_permissions_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
